use_frameworks!
inhibit_all_warnings!

abstract_target 'GuitarTarget' do
    pod 'Guitar', path: '../'

    target 'GuitarExample-iOS' do
        target 'GuitarExampleTests' do
        end
    end

    target 'GuitarExample-Mac' do
    end

    target 'GuitarExample-TV' do
    end

    target 'GuitarExample-Watch' do
        target 'GuitarExample-Watch Extension' do
        end
    end
end
