use_frameworks!
inhibit_all_warnings!

abstract_target 'GuitarTarget' do
    pod 'Guitar', path: '../'

    target 'GuitarExample' do
    end

    target 'GuitarExample-Mac' do
    end

    target 'GuitarExample-TV' do
    end

    target 'GuitarExample-Watch' do
    end

    target 'GuitarExample-Watch Extension' do
    end

    target 'GuitarExampleTests' do
    end

end
